import { CandidateProfile, JobConfig, AssessmentReport } from "../types/interview";

export const DEMO_CANDIDATE: CandidateProfile = {
  id: "cand_alex_chen_01",
  name: "Alex Chen",
  email: "alex.chen.dev@example.com",
  targetRole: "Senior Distributed Systems Engineer",
  yearsOfExperience: 6,
  skills: [
    "Distributed Systems",
    "Go",
    "TypeScript",
    "Rust",
    "PostgreSQL",
    "Kafka",
    "Redis",
    "Kubernetes",
    "System Design",
    "API Latency Optimization",
  ],
  technologies: ["Go", "Docker", "K8s", "Redis Cluster", "gRPC", "Envoy", "Prometheus", "Kafka"],
  domains: ["FinTech", "High-Throughput Payments", "Real-Time Streaming"],
  education: [
    {
      degree: "B.S. in Computer Science",
      institution: "University of Washington",
      year: 2019,
    },
  ],
  experience: [
    {
      role: "Senior Software Engineer",
      company: "Aura Payments Inc.",
      period: "2021 - Present",
      highlights: [
        "Re-architected core settlement pipeline to process 35,000 tx/sec with p99 latency < 28ms.",
        "Implemented multi-tiered Redis caching layer reducing database read load by 68%.",
        "Led incident post-mortems and authored distributed tracing standards across 8 backend squads.",
      ],
    },
    {
      role: "Software Engineer",
      company: "CloudScale Technologies",
      period: "2019 - 2021",
      highlights: [
        "Developed high-throughput gRPC microservices handling customer ledger mutations.",
        "Created an automated chaos engineering testing harness with Toxiproxy and Kubernetes.",
      ],
    },
  ],
  projects: [
    {
      name: "FluxCache: Distributed Invalidation Gateway",
      description: "Open-source CDC-driven cache synchronization daemon supporting Redis and Memcached.",
      impact: "Eliminated stale read anomalies across secondary replicas under heavy write churn.",
      techStack: ["Go", "Kafka", "Redis", "Protobuf"],
    },
  ],
  achievements: [
    "AWS Certified Solutions Architect - Professional",
    "Speaker at GopherCon 2023 on 'Zero-Downtime Cache Warmups'",
  ],
  certifications: ["AWS Certified Solutions Architect", "CKA - Certified Kubernetes Administrator"],
};

export const DEMO_JOBS: JobConfig[] = [
  {
    id: "job_swe_sr_01",
    title: "Senior Distributed Systems Engineer",
    department: "Core Infrastructure & Platform",
    description: "Design and scale real-time distributed settlement engines handling millions of concurrent events.",
    requiredSkills: ["Distributed Systems", "Go or Rust", "Kafka/Event Streaming", "Caching Strategies"],
    preferredSkills: ["Kubernetes", "Prometheus/OpenTelemetry", "High-Availability Datastores"],
    experienceLevel: "Senior",
    durationMinutes: 30,
    difficulty: 3,
    competencies: [
      "Technical Depth & Architecture",
      "Problem Solving & Tradeoffs",
      "Product & Customer Impact",
      "Leadership & Ownership",
      "Communication & Clarity",
    ],
    panelConfig: [
      { role: "technical", weight: 40, enabled: true, order: 1 },
      { role: "product", weight: 25, enabled: true, order: 2 },
      { role: "behavioral", weight: 20, enabled: true, order: 3 },
      { role: "hiring_manager", weight: 15, enabled: true, order: 4 },
      { role: "customer", weight: 0, enabled: false, order: 5 },
    ],
  },
  {
    id: "job_lead_fullstack_02",
    title: "Lead Full-Stack Architect",
    department: "Enterprise Solutions",
    description: "Lead end-to-end technical execution of customer-facing enterprise collaboration software.",
    requiredSkills: ["React", "TypeScript", "Node.js", "System Design", "Cloud Infrastructure"],
    preferredSkills: ["GraphQL", "WebSockets/WebRTC", "CI/CD Orchestration"],
    experienceLevel: "Lead",
    durationMinutes: 45,
    difficulty: 4,
    competencies: [
      "Technical Depth",
      "Product Thinking",
      "Stakeholder Communication",
      "Ownership & Mentorship",
      "Client Management",
    ],
    panelConfig: [
      { role: "technical", weight: 35, enabled: true, order: 1 },
      { role: "product", weight: 25, enabled: true, order: 2 },
      { role: "customer", weight: 20, enabled: true, order: 3 },
      { role: "hiring_manager", weight: 20, enabled: true, order: 4 },
      { role: "behavioral", weight: 0, enabled: false, order: 5 },
    ],
  },
];

export const DEMO_PRECOMPLETED_ASSESSMENT: AssessmentReport = {
  id: "rep_demo_982",
  interviewId: "sess_demo_live_01",
  candidateName: "Alex Chen",
  jobTitle: "Senior Distributed Systems Engineer",
  completedAt: new Date(Date.now() - 3600000).toISOString(),
  durationFormatted: "24m 18s",
  overallScore: 82,
  competencyScores: [
    { name: "Technical Depth", score: 88, benchmark: 75 },
    { name: "Product Thinking", score: 71, benchmark: 70 },
    { name: "Communication", score: 84, benchmark: 75 },
    { name: "Leadership & Ownership", score: 78, benchmark: 70 },
    { name: "Problem Solving", score: 89, benchmark: 75 },
  ],
  strengths: [
    "Outstanding clarity explaining cache invalidation trade-offs and distributed lock contention.",
    "Proactively highlighted edge cases in partition-tolerant distributed transactions.",
    "Responsive and collaborative demeanor when challenged on non-functional requirements.",
  ],
  weaknesses: [
    "Initially lacked customer impact quantification for latency reduction until prompted by Product Manager.",
    "Some answers around team ownership initially conflated solo work with team design decisions.",
  ],
  recommendation: "Hire",
  evidenceList: [
    {
      id: "ev_01",
      interviewId: "sess_demo_live_01",
      competency: "Technical Depth",
      claim: "Demonstrated thorough mastery of cache invalidation under write heavy workloads",
      evidence: "Candidate explained sliding window TTLs combined with CDC invalidation events via Kafka.",
      score: 92,
      transcriptStart: 124,
      transcriptEnd: 188,
      confidence: 0.95,
      vaguenessScore: 0.12,
    },
    {
      id: "ev_02",
      interviewId: "sess_demo_live_01",
      competency: "Product Thinking",
      claim: "Understood technical latency reduction but weakly connected it to checkout conversion rates initially",
      evidence: "Stated 'we made the service faster' without baseline metrics until Elena probed for user conversion impact.",
      score: 68,
      transcriptStart: 240,
      transcriptEnd: 310,
      confidence: 0.88,
      vaguenessScore: 0.65,
    },
    {
      id: "ev_03",
      interviewId: "sess_demo_live_01",
      competency: "Leadership & Ownership",
      claim: "Clarified personal role from broader architecture team after initial overstatement",
      evidence: "Candidate accurately recalibrated from 'I designed the entire system' to owning the Kafka ingest pipeline.",
      score: 79,
      transcriptStart: 380,
      transcriptEnd: 430,
      confidence: 0.91,
      isContradiction: true,
    },
  ],
  interviewerPerspectives: [
    {
      role: "technical",
      interviewerName: "Dr. Marcus Vance",
      title: "Principal Staff Systems Architect",
      score: 89,
      verdict: "Strong Yes",
      quote: "Demonstrated deep mastery of memory limits, cache stampede prevention, and partition tolerance.",
      perspective: "Alex showed genuine engineering seniority. When I probed on what would happen if Redis cluster replicas lagged, he immediately discussed monotonic read consistency and fallback strategies rather than dodging.",
    },
    {
      role: "product",
      interviewerName: "Elena Rostova",
      title: "Head of Product Strategy",
      score: 72,
      verdict: "Leaning Yes",
      quote: "Needed direct prompting to connect technical optimizations to business outcomes, but recovered well.",
      perspective: "When Alex first discussed shaving 40ms off API response times, he framed it as purely an infrastructure win. Once I challenged him on customer impact, he recognized how this improved mobile checkout completion by 3.4%.",
    },
    {
      role: "behavioral",
      interviewerName: "Devon Clark",
      title: "Director of Engineering Operations",
      score: 83,
      verdict: "Yes",
      quote: "High self-awareness during conflict post-mortems and mature ownership of past outages.",
      perspective: "I was impressed by his candor regarding an earlier production deployment failure. Instead of finger-pointing at junior developers or QA, he walked through how he added pre-flight smoke tests to prevent recurrence.",
    },
    {
      role: "hiring_manager",
      interviewerName: "Sarah Jenkins",
      title: "VP of Engineering",
      score: 85,
      verdict: "Strong Hire",
      quote: "Strong cultural alignment, high leverage, and readiness to lead complex technical initiatives.",
      perspective: "Alex exhibits the right combination of technical depth and desire for impact. With senior mentorship, he will quickly become a core technical anchor for our distributed infrastructure group.",
    },
  ],
  transcriptSummary: "24-minute panel interview covering system architecture, caching strategies, customer impact attribution, outage retrospectives, and engineering leadership.",
};
